from .TestCase import TestCase
from .CoursesTestCase import CoursesTestCase
from .CourseTestCase import CourseTestCase
from .PostCoursesTestCase import PostCoursesTestCase
from .PostCourseTestCase import PostCourseTestCase
from .TeachersTestCase import TeachersTestCase
from .TeacherTestCase import TeacherTestCase
from .HomepageTestCase import HomepageTestCase
from .SearchTestCase import SearchTestCase
from .SeriesCourseTestCase import SeriesCourseTestCase
from .PersonalCenterTestCase import PersonalCenterTestCase
