from .Page import Page
from .Courses import Courses
from .Login import Login
from .Course import Course
from .PostCourses import PostCourses
from .PostCourse import PostCourse
from .Teachers import Teachers
from .Teacher import Teacher
from .Homepage import Homepage
from .Search import Search
from .SeriesCourse import SeriesCourse
from .PersonalCenter import PersonalCenter
from .Bbs import Bbs
from .BbsPlate import BbsPlate
from .BbsPost import BbsPost
